http:
  basePath: "/api/v1/*"
  host: "0.0.0.0"
  port: "8083"
  consolePath: "/console/*"
  
calm2:
  host: "0.0.0.0"
  port: "8081"
  basePath: "/api/v1"
  path: "/erpOrderLines"
  client_id: "123"
  client_secret: "123"  
  
api:
  discovery:
    id: ""
         
cloudhub:
  username: ""
  password: ""
  
smtp:
  host: ""
  port: ""
  user: ""
  password: ""
  subject: ""


db:
 audit: 
  config:
   host: "db-audit-demo.czox2kq9otxp.eu-west-1.rds.amazonaws.com"
   port: "3306"
   user: "![SMja/nV+bgct1YakjpE9Dw==]"
   password: "![s+9bS/QnD6wOPefrjUqlhA==]"
   database: "sys" 
    
sqs:
  accessKey: ""
  secretKey: ""
  region: ""
